#!/bin/bash 

change_apt() {
package_editor=$(dialog --title "Write here command to update system" --inputbox "for example pacman -Suy" 10 50 3 2&1 >/dev/tty)
}
Error=$(dialog --title "Error!" --msgbox "You have un error, Restart script and try again" 2&1 >/dev/tty) 
menu_main2=$(dialog --menu "Is advanset options for MENU" \
  1 "Edit pakcage manager" \
  2 "Restart program" \
  3 "Exit to main menu" 10 50 3 2&1 > /dev/tty) 
case menu_main in 
  1) package_editor
